import 'package:flutter/material.dart';

class Food {
  final String title, image, description;
  final int price, id, size;
  final Color color;
  Food(
      {this.color,
      this.description,
      this.id,
      this.image,
      this.price,
      this.size,
      this.title});
}

List<Food> Foods = [
  Food(
    id: 1,
    title: "Jellof Rice",
    size: 12,
    description: "very good fasinator",
    price: 5000,
    image: "images/Food.jpg",
    color: Color(0xFF6D7A41),
  ),
  Food(
    id: 2,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 8400,
    image: "images/Food1.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 3,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 11000,
    image: "images/Food2.jpg",
    color: Color(0xFF2D4350),
  ),
  Food(
    id: 4,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 5400,
    image: "images/Food3.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 5,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 5800,
    image: "images/Food4.jpg",
    color: Color(0xFF040406),
  ),
  Food(
    id: 6,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 5900,
    image: "images/Food5.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 7,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 7500,
    image: "images/Food6.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 8,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 6000,
    image: "images/Food7.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 9,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 8000,
    image: "images/Food8.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 10,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 6000,
    image: "images/Food9.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 11,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 5500,
    image: "images/Food10.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 12,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 9000,
    image: "images/Food11.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 13,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 4500,
    image: "images/Food12.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 14,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 8000,
    image: "images/Food13.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 14,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 8000,
    image: "images/Food14.jpg",
    color: Color(0xFF577365),
  ),
  Food(
    id: 14,
    title: "Outing outfit",
    size: 12,
    description: "very good fasinator",
    price: 8000,
    image: "images/Food15.jpg",
    color: Color(0xFF577365),
  ),
];
